title: Green Skill Project
description: This website provides supporting materials for the green skill project.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
      # zip_url: http://example.com/download.zip
      index_url: https://github.com/yangcheng258/green-skill-project/blob/09e0220780257aa422f4f990409fe3ae564cb1bf/_data/S3_occupational_green_potential.csv
      # project1_url: https://github.com/yangcheng258/green-skill-recommendation/blob/d6f338d7aea2387a89014a9806dc5631b86f5a8e/_data/S3_occupational_green_potential.csv

